### ISSUE TITLE
Investigate importing banter from spreadsheet

### ISSUE THREAD

**Issue by jcraigk** [jcraigk/phishin#124]
https://docs.google.com/spreadsheets/d/11TkKV1ECCfbtst-kcOJYHvW5XlommfeL0-aJ8rLDq_w/htmlview

`@trey_speaks` on twitter

**Comment by ucpete** [comment]
> [@trey_talks](https://twitter.com/trey_talks)

FTFY

**Comment by jcraigk** [comment]
Related to #318, which supersedes this issue.
