### ISSUE TITLE
Jamcharts (and probably other tags) using same description if multiple exist (Soundcheck?)

### ISSUE THREAD

**Issue by chrisbendel** [jcraigk/phishin#127]
I see #89 but unsure if it's been pushed to prod or not.  

http://phish.in/1998-11-27  

Example here with wipeout. Soundcheck & Second set have the same jamcharts description. Unsure if this was just missed for soundcheck sections, since it looks like 89 solves this issue generally.  

  
Probably an easy fix, just pointing it out for you.

**Comment by jcraigk** [comment]
Thanks for pointing out this example; should help in getting this debugged.  #89 has not been addressed yet, hopefully will get to it soon.
