### ISSUE TITLE
Rubocop Refactoring

### ISSUE THREAD

**Issue by jcraigk** [jcraigk/phishin#150]
See https://github.com/jcraigk/phishin/blob/master/.rubocop_todo.yml

**Comment by ChefAustin** [comment]
Link is dead because`.rubocop_todo.yml` doesn't seem to exist anymore. Has this issue already been closed or is the file just missing from the repo?

**Comment by jcraigk** [comment]
Oh yep this has already been done, thanks for pointing it out.
