### ISSUE TITLE
Create and populate Weather Tag

### ISSUE THREAD

**Issue by jcraigk** [jcraigk/phishin#154]
Tag for applying to Shows that talks about weather (rain, wind, etc) that might cause audio issues or delays, etc.  For example:

Ones I happen to know about:
http://phish.in/2019-07-06
http://phish.in/2019-06-25
http://phish.in/2011-06-15
http://phish.in/2013-07-12
https://phish.in/2013-07-19

**Comment by ucpete** [comment]
See phish.net show notes for these ones too:

http://phish.in/1993-07-22
http://phish.in/1997-07-22
http://phish.in/1999-07-01
http://phish.in/2000-07-03
http://phish.in/2009-06-19
http://phish.in/2013-07-21

**Comment by jcraigk** [comment]
Done http://phish.in/tags/weather
