### ISSUE TITLE
HTTP is not redirected to HTTPS

### ISSUE THREAD

**Issue by twoversionsofme** [jcraigk/phishin#180]
I recently signed up for an account on phish.in and then realized today that my bookmark for the site used the URL "phish.in" which uses the http version of the site.  It appears that the site uses cloudflare CDN and thus has a certificate on the https version, but the http traffic isn't being forwarded to https.  Since usernames and passwords could be included in communication, I think it best to use https only.

**Comment by jcraigk** [comment]
Good point, I just flipped the switch so all traffic should be SSL only now.
