### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by robhagopian** [jcraigk/phishin#183]
Request for Android Auto support. Would be absolutely fantastic!

**Comment by robhagopian** [comment]
I've read through https://developer.android.com/training/cars/media but I don't really have a good idea of how much work this is

**Comment by jcraigk** [comment]
That's a great idea!  See https://github.com/mikevoyt/RoboPhish for an example of another Android project that uses the Phish.in API as its backend.  You would be looking at either adding to an existing Android project or starting your own and then running that software in the car.  It would make HTTP requests to the Phish.in API as described at https://phish.in/api-docs.

Closing the issue as this doesn't pertain directly to the Phish.in web/api repo.
