### ISSUE TITLE
Guest tag (and possibly others) breaks on apostrophes

### ISSUE THREAD

**Issue by ucpete** [jcraigk/phishin#202]
See either of Tim O'Brien's appearances, e.g. 7/1/99:
![image](https://user-images.githubusercontent.com/943217/77198619-8febd680-6aa4-11ea-97fb-ba193a804ab0.png)

**Comment by jcraigk** [comment]
This is actually a data issue, looks like this broke on import.  Other instances imported just fine, so I'm chalking it up to a one-off issue in the data source (which was based on https://phish.net/charts/guest I believe).  Good find.
