### ISSUE TITLE
Incorrect song_ids on track 28713

### ISSUE THREAD

**Issue by jlmayfield** [jcraigk/phishin#270]
Track 28713 (Good Times, Bad Times from Encode 4/13/94) has song_ids containing both the id for Good TImes, Bad Times and the id for Rift.  It's definitely not a Good TImes, Bad Times > Rift track or anything like nor can I hear a tease for Rift.  Seems like error in the data.

**Comment by jcraigk** [comment]
Fixed, thanks for the heads up
