### ISSUE TITLE
Sort by year 1995 is missing 5/16/95 on site, works on Android app

### ISSUE THREAD

**Issue by phishgithub** [jcraigk/phishin#291]
Subject says it all, noticed this when I went to listen to 5/16/95 in Lowell, MA on the app and then couldn't find it when I sort by year > 1995 on site:

Show:
https://phish.in/1995-05-16

Sort by 95:
https://phish.in/1995

Maybe because it is not part of the 95 summer tour grouping but was a standalone benefit show

**Comment by jcraigk** [comment]
The year pages are indeed grouped by tour. You have to scroll down the page to see the content you're looking for:

<img width="715" alt="Screenshot 2022-12-24 at 12 10 57 AM" src="https://user-images.githubusercontent.com/104095/209427232-2cef4666-e8ba-4fbc-89b4-537f390c73b9.png">
