### ISSUE TITLE
Podcast feeds

### ISSUE THREAD

**Issue by GreenLunar** [jcraigk/phishin#299]
Please add support for ATOM or RSS feeds so it would be possible to get notified on updates directly from mobile and desktop podcast managers, and other music collection managers that support rss/podcast feeds.

**Comment by GreenLunar** [comment]
Thank you!

To make the RSS feed auto-discoverable, you can use this:
```
<link href='http://phish.in/feeds/rss' title='Phish.in Updates' rel='alternate' type='application/rss+xml'>
```

**Comment by jcraigk** [comment]
Good call, all set.
