### ISSUE TITLE
Playlist feature not fully functional?

### ISSUE THREAD

**Issue by PlaylistBoy** [jcraigk/phishin#320]
Hello! 

There seem to be several issues with the playlist feature on the site right now. My standing system is Windows 10 on PC, using Chrome. But I also replicated this on Windows 10/PC/Firefox as well as Chrome on Android mobile.

There are a couple of different issues I've noticed...

The "active playlist" will only allow one show to be added. So, for example, my plan was to put all four nights of this year's Dick's shows into an active playlist, remove anything that didn't grab me, and then save as a "best of Dick's 2023." But any time I click on a new show to add it, that becomes the only show in the playlist. Clicking on any show automatically adds it to the active playlist, which means that going into the show and adding individual songs seems out of the question. Trying to add an entire show via the little dropdown arrow that appears next to the venue leads to the same result in that whatever the most recent one you add is, that's the entirety of that playlist, with the one that was added previously being wiped out.

Trying to save an "active playlist" to an existing one also doesn't work, as the dropdown for "update existing playlist" appears but isn't selectable. (I also don't know if the arrows on shows and songs are supposed to allow for you to add those directly to existing playlists or not, but if they are, it doesn't even show the option.)

I've only attached a screenshot for the "update existing playlist" bug because I'm not sure how to illustrate the other issues visually, but I HOPE I explained it well enough. I'm wayoutstuff in the Discord if you need to get a hold of me, too!

Thank you, and I hope I'm actually pointing out a bug and not just wishing for functionality that never existed in the first place and thus wasting your time!
![update existing playlist](https://github.com/jcraigk/phishin/assets/145394366/10d1f1d7-90a0-4428-a33e-d9f9f349b06f)

**Comment by jcraigk** [comment]
That screenshot shows an Untitled Playlist, so the only option would be to save it as a new one. I updated the language slightly to make this a bit clearer.

<img width="580" alt="Screenshot 2023-09-20 at 10 38 06 PM" src="https://github.com/jcraigk/phishin/assets/104095/59c90d3d-1366-4480-b313-68e0de3d8244">

I tested and the save features seem to be working as designed. Let me know if you run into issues though.
