### ISSUE TITLE
Update prevents continuous playing of songs

### ISSUE THREAD

**Issue by bonnelll** [jcraigk/phishin#331]
After the recent update, the next song no longer plays after the previous song finishes. It requires clicking each song to play. I hope this is not an intentional update as I will stop using the site. Thanks

**Comment by jcraigk** [comment]
Hi thanks for the report. Can you share what OS and browser versions you are using. Mobile or desktop? Are there any errors in the Javascript console if you have access to that?

**Comment by bonnelll** [comment]
Thanks for the quick response. I'm using Windows Desktop, Google Chrome. I don't see any errors in the javascript console. This just started happening yesterday.

**Comment by jcraigk** [comment]
Thanks for the detail. I rolled back to 2e869950381cecbb6834766ee1c2b79ab35c4289 for now, which should fix the issue, and will look at a longer term fix later.

**Comment by bonnelll** [comment]
Thanks so much!!
