### ISSUE TITLE
Phish 9/2/22 Unable to Download 1st Five Songs

### ISSUE THREAD

**Issue by DisceauxD** [jcraigk/phishin#384]
Hi, Gang!

I appreciate all the hard work you have put into this project! Quite remarkable.

I've tried numerous times, but alas I am unable to download the mp3s of the first five songs (Carini thru Reba) of the 9/2/22 show. I had no problem downloading all the other songs for this gig, as well as countless other shows.

Thanks for your help with this! It was my soon-to-be 8-year-old son's first Phish show ever (Sadly because of the excessive weather delay. He managed to fall asleep during YEM...after the glowsticks!). He's excited for his 4th show coming up on 8/30/24!

Disceaux D

**Comment by jcraigk** [comment]
Hey there, thanks for the note. I just cleared the CloudFlare CDN cache on those tracks, can you try it again? What browser/platform are you on? Can you replicate on another browser?

If all else fails, you can find most MP3s on the [Phish Downloads Spreadsheet](https://docs.google.com/spreadsheets/d/1yAXu83gJBz08cW5OXoqNuN1IbvDXD2vCrDKj4zn1qmU/edit?gid=7#gid=7) as well.

**Comment by DisceauxD** [comment]
Hi, Justin!

Thanks for the help. I was using Google Chrome browser, and it still didn't
work after you cleared the cache. However, I tried it on my Safari browser,
and it worked fine. So, I got what I wanted.

Since you mentioned it, I have tried to access shows via Phish Downloads
Spreadsheet, but I must be doing something wrong. Whether I use Chrome or
Safari, when I click on a show's "download link," it downloads/saves the
entire show to my MacBook Pro's "Downloads" folder as a .rar file, not a
zip or mp3 or FLAC. I am not able to open a .rar file, so I'm not sure
what to do. For example, "1996-04-28 - Jimmys - New Orleans, LA.rar" is
158.9 MB & listed as a "music document" (as opposed to mp3 or FLAC) in my
Downloads folder. "1994-06-30 - Classic Amphitheater - Richmond, VA.rar" is
296.2 MB & also listed as a "music document." When I double-click on them,
nothing happens. What am I missing here?

I can listen to FLAC files (which I know are superior to mp3 files) on my
QuickTime Player on my Macbook Pro (thanks to "See the Zoo" spreadsheet
with FLAC recordings), but I also want to listen to shows on my iPhone when
I'm walking my dog, etc. It would be great to listen to FLAC when I'm doing
this, but it seems with using my Apple AirPods & iPhone, I would have to
listen to mp3 (or WAV) through my iTunes (Apple Music), correct?

Could you please help me understand how to access shows via Phish Downloads
Spreadsheet and offer any other suggestions to accomplish what I'm trying
to do?

Thanks again for your help!

Faithfully,
David Musser
504.615.0001 (c)

**Comment by jcraigk** [comment]
If you're on a mac, you'll need to download a program to open RAR files, which are compressed files like ZIP. There are several Mac programs available, I would recommend a google or App Store search. Also for listening to FLAC I recommend using [VLC Player](https://www.videolan.org/).
