### ISSUE TITLE
z-index for show dropdown is wrong

### ISSUE THREAD

**Issue by alexebird** [jcraigk/phishin#5]
The "add to playlist"/"share"/"lookup at phish.net" dropdown in the lefthand column on a show's page (http://phish.in/2013-12-29) is getting rendered underneath set list content area.
![phishin-bug](https://cloud.githubusercontent.com/assets/120678/3055684/9bf01060-e1c3-11e3-9558-9614a06c7041.png)

**Comment by jcraigk** [comment]
Fixed in https://github.com/jcraigk/phishin/pull/113
